version: "3"
services:
  neuralqa:
    build: .
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    ports:
      - "80:80"
    expose:
      - 80
